const MARSER_VERSION = "0.2.1";

export function cargoToml(projectName) {
  return `[package]
name = "${projectName}"
version = "0.1.0"
edition = "2024"

[dependencies]
marser = "${MARSER_VERSION}"
`;
}

export function mainRs() {
  return `use marser::parser::Parser;

mod grammar;

fn main() {
    let input = std::io::read_to_string(std::io::stdin()).expect("failed to read stdin");
    match grammar::grammar().parse_str(&input) {
        Ok(_) => println!("OK"),
        Err(err) => {
            eprintln!("{err}");
            std::process::exit(1);
        }
    }
}
`;
}

export function readme(projectName, entryRule) {
  const entry = entryRule.trim() || "(last rule in grammar)";
  return `# ${projectName}

Generated by [pest-to-marser](https://github.com/ArneCode/marser).

## Entry rule

\`${entry}\`

## Build and run

\`\`\`sh
cargo build
echo 'your input' | cargo run
\`\`\`

The parser accepts input on stdin and prints \`OK\` on success.
`;
}
